/* eslint-disable no-undef, no-unused-expressions */
const { expect } = require('chai');
require('chai').use(require('sinon-chai'));
const PullRequest = require('../src/models/PullRequest');

describe('PullRequest model', () => {
  const repoPullRequest = new PullRequest({
    url: 'https://api.github.com/repos/ski-ski/skiski-app/pulls/1',
    id: 127281741,
    html_url: 'https://github.com/ski-ski/skiski-app/pull/1',
    diff_url: 'https://github.com/ski-ski/skiski-app/pull/1.diff',
    patch_url: 'https://github.com/ski-ski/skiski-app/pull/1.patch',
    issue_url: 'https://api.github.com/repos/ski-ski/skiski-app/issues/1',
    number: 1,
    state: 'closed',
    locked: false,
    title: 'users migration file ',
    user: {
      login: 'michaelmurray6298',
      id: 24865792,
      avatar_url: 'https://avatars1.githubusercontent.com/u/24865792?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/michaelmurray6298',
      html_url: 'https://github.com/michaelmurray6298',
      followers_url: 'https://api.github.com/users/michaelmurray6298/followers',
      following_url: 'https://api.github.com/users/michaelmurray6298/following{/other_user}',
      gists_url: 'https://api.github.com/users/michaelmurray6298/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/michaelmurray6298/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/michaelmurray6298/subscriptions',
      organizations_url: 'https://api.github.com/users/michaelmurray6298/orgs',
      repos_url: 'https://api.github.com/users/michaelmurray6298/repos',
      events_url: 'https://api.github.com/users/michaelmurray6298/events{/privacy}',
      received_events_url: 'https://api.github.com/users/michaelmurray6298/received_events',
      type: 'User',
      site_admin: false,
    },
    body: '',
    created_at: '2017-06-23T20:21:34Z',
    updated_at: '2017-06-23T20:22:10Z',
    closed_at: '2017-06-23T20:22:10Z',
    merged_at: '2017-06-23T20:22:10Z',
    merge_commit_sha: '338f9d7258bbaf3d83ed1d5ba959ab1d8084ccde',
    assignee: null,
    assignees: [],
    requested_reviewers: [],
    milestone: null,
    commits_url: 'https://api.github.com/repos/ski-ski/skiski-app/pulls/1/commits',
    review_comments_url: 'https://api.github.com/repos/ski-ski/skiski-app/pulls/1/comments',
    review_comment_url: 'https://api.github.com/repos/ski-ski/skiski-app/pulls/comments{/number}',
    comments_url: 'https://api.github.com/repos/ski-ski/skiski-app/issues/1/comments',
    statuses_url: 'https://api.github.com/repos/ski-ski/skiski-app/statuses/c10c31f9d902c9f60e6d6d964f23d66db087e8ea',
    head: {
      label: 'ski-ski:dev',
      ref: 'dev',
      sha: 'c10c31f9d902c9f60e6d6d964f23d66db087e8ea',
      user: {
        login: 'ski-ski',
        id: 29638033,
        avatar_url: 'https://avatars3.githubusercontent.com/u/29638033?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/ski-ski',
        html_url: 'https://github.com/ski-ski',
        followers_url: 'https://api.github.com/users/ski-ski/followers',
        following_url: 'https://api.github.com/users/ski-ski/following{/other_user}',
        gists_url: 'https://api.github.com/users/ski-ski/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/ski-ski/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/ski-ski/subscriptions',
        organizations_url: 'https://api.github.com/users/ski-ski/orgs',
        repos_url: 'https://api.github.com/users/ski-ski/repos',
        events_url: 'https://api.github.com/users/ski-ski/events{/privacy}',
        received_events_url: 'https://api.github.com/users/ski-ski/received_events',
        type: 'Organization',
        site_admin: false,
      },
      repo: {
        id: 95143360,
        name: 'skiski-app',
        full_name: 'ski-ski/skiski-app',
        owner: {
          login: 'ski-ski',
          id: 29638033,
          avatar_url: 'https://avatars3.githubusercontent.com/u/29638033?v=4',
          gravatar_id: '',
          url: 'https://api.github.com/users/ski-ski',
          html_url: 'https://github.com/ski-ski',
          followers_url: 'https://api.github.com/users/ski-ski/followers',
          following_url: 'https://api.github.com/users/ski-ski/following{/other_user}',
          gists_url: 'https://api.github.com/users/ski-ski/gists{/gist_id}',
          starred_url: 'https://api.github.com/users/ski-ski/starred{/owner}{/repo}',
          subscriptions_url: 'https://api.github.com/users/ski-ski/subscriptions',
          organizations_url: 'https://api.github.com/users/ski-ski/orgs',
          repos_url: 'https://api.github.com/users/ski-ski/repos',
          events_url: 'https://api.github.com/users/ski-ski/events{/privacy}',
          received_events_url: 'https://api.github.com/users/ski-ski/received_events',
          type: 'Organization',
          site_admin: false,
        },
        private: false,
        html_url: 'https://github.com/ski-ski/skiski-app',
        description: null,
        fork: false,
        url: 'https://api.github.com/repos/ski-ski/skiski-app',
        forks_url: 'https://api.github.com/repos/ski-ski/skiski-app/forks',
        keys_url: 'https://api.github.com/repos/ski-ski/skiski-app/keys{/key_id}',
        collaborators_url: 'https://api.github.com/repos/ski-ski/skiski-app/collaborators{/collaborator}',
        teams_url: 'https://api.github.com/repos/ski-ski/skiski-app/teams',
        hooks_url: 'https://api.github.com/repos/ski-ski/skiski-app/hooks',
        issue_events_url: 'https://api.github.com/repos/ski-ski/skiski-app/issues/events{/number}',
        events_url: 'https://api.github.com/repos/ski-ski/skiski-app/events',
        assignees_url: 'https://api.github.com/repos/ski-ski/skiski-app/assignees{/user}',
        branches_url: 'https://api.github.com/repos/ski-ski/skiski-app/branches{/branch}',
        tags_url: 'https://api.github.com/repos/ski-ski/skiski-app/tags',
        blobs_url: 'https://api.github.com/repos/ski-ski/skiski-app/git/blobs{/sha}',
        git_tags_url: 'https://api.github.com/repos/ski-ski/skiski-app/git/tags{/sha}',
        git_refs_url: 'https://api.github.com/repos/ski-ski/skiski-app/git/refs{/sha}',
        trees_url: 'https://api.github.com/repos/ski-ski/skiski-app/git/trees{/sha}',
        statuses_url: 'https://api.github.com/repos/ski-ski/skiski-app/statuses/{sha}',
        languages_url: 'https://api.github.com/repos/ski-ski/skiski-app/languages',
        stargazers_url: 'https://api.github.com/repos/ski-ski/skiski-app/stargazers',
        contributors_url: 'https://api.github.com/repos/ski-ski/skiski-app/contributors',
        subscribers_url: 'https://api.github.com/repos/ski-ski/skiski-app/subscribers',
        subscription_url: 'https://api.github.com/repos/ski-ski/skiski-app/subscription',
        commits_url: 'https://api.github.com/repos/ski-ski/skiski-app/commits{/sha}',
        git_commits_url: 'https://api.github.com/repos/ski-ski/skiski-app/git/commits{/sha}',
        comments_url: 'https://api.github.com/repos/ski-ski/skiski-app/comments{/number}',
        issue_comment_url: 'https://api.github.com/repos/ski-ski/skiski-app/issues/comments{/number}',
        contents_url: 'https://api.github.com/repos/ski-ski/skiski-app/contents/{+path}',
        compare_url: 'https://api.github.com/repos/ski-ski/skiski-app/compare/{base}...{head}',
        merges_url: 'https://api.github.com/repos/ski-ski/skiski-app/merges',
        archive_url: 'https://api.github.com/repos/ski-ski/skiski-app/{archive_format}{/ref}',
        downloads_url: 'https://api.github.com/repos/ski-ski/skiski-app/downloads',
        issues_url: 'https://api.github.com/repos/ski-ski/skiski-app/issues{/number}',
        pulls_url: 'https://api.github.com/repos/ski-ski/skiski-app/pulls{/number}',
        milestones_url: 'https://api.github.com/repos/ski-ski/skiski-app/milestones{/number}',
        notifications_url: 'https://api.github.com/repos/ski-ski/skiski-app/notifications{?since,all,participating}',
        labels_url: 'https://api.github.com/repos/ski-ski/skiski-app/labels{/name}',
        releases_url: 'https://api.github.com/repos/ski-ski/skiski-app/releases{/id}',
        deployments_url: 'https://api.github.com/repos/ski-ski/skiski-app/deployments',
        created_at: '2017-06-22T18:08:21Z',
        updated_at: '2017-06-23T22:48:38Z',
        pushed_at: '2017-08-03T02:23:38Z',
        git_url: 'git://github.com/ski-ski/skiski-app.git',
        ssh_url: 'git@github.com:ski-ski/skiski-app.git',
        clone_url: 'https://github.com/ski-ski/skiski-app.git',
        svn_url: 'https://github.com/ski-ski/skiski-app',
        homepage: null,
        size: 472,
        stargazers_count: 0,
        watchers_count: 0,
        language: 'JavaScript',
        has_issues: true,
        has_projects: true,
        has_downloads: true,
        has_wiki: true,
        has_pages: false,
        forks_count: 0,
        mirror_url: null,
        open_issues_count: 2,
        forks: 0,
        open_issues: 2,
        watchers: 0,
        default_branch: 'master',
      },
    },
    base: {
      label: 'ski-ski:master',
      ref: 'master',
      sha: 'cb720430aba752561d45b9d41fba65b41dda80f4',
      user: {
        login: 'ski-ski',
        id: 29638033,
        avatar_url: 'https://avatars3.githubusercontent.com/u/29638033?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/ski-ski',
        html_url: 'https://github.com/ski-ski',
        followers_url: 'https://api.github.com/users/ski-ski/followers',
        following_url: 'https://api.github.com/users/ski-ski/following{/other_user}',
        gists_url: 'https://api.github.com/users/ski-ski/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/ski-ski/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/ski-ski/subscriptions',
        organizations_url: 'https://api.github.com/users/ski-ski/orgs',
        repos_url: 'https://api.github.com/users/ski-ski/repos',
        events_url: 'https://api.github.com/users/ski-ski/events{/privacy}',
        received_events_url: 'https://api.github.com/users/ski-ski/received_events',
        type: 'Organization',
        site_admin: false,
      },
      repo: {
        id: 95143360,
        name: 'skiski-app',
        full_name: 'ski-ski/skiski-app',
        owner: {
          login: 'ski-ski',
          id: 29638033,
          avatar_url: 'https://avatars3.githubusercontent.com/u/29638033?v=4',
          gravatar_id: '',
          url: 'https://api.github.com/users/ski-ski',
          html_url: 'https://github.com/ski-ski',
          followers_url: 'https://api.github.com/users/ski-ski/followers',
          following_url: 'https://api.github.com/users/ski-ski/following{/other_user}',
          gists_url: 'https://api.github.com/users/ski-ski/gists{/gist_id}',
          starred_url: 'https://api.github.com/users/ski-ski/starred{/owner}{/repo}',
          subscriptions_url: 'https://api.github.com/users/ski-ski/subscriptions',
          organizations_url: 'https://api.github.com/users/ski-ski/orgs',
          repos_url: 'https://api.github.com/users/ski-ski/repos',
          events_url: 'https://api.github.com/users/ski-ski/events{/privacy}',
          received_events_url: 'https://api.github.com/users/ski-ski/received_events',
          type: 'Organization',
          site_admin: false,
        },
        private: false,
        html_url: 'https://github.com/ski-ski/skiski-app',
        description: null,
        fork: false,
        url: 'https://api.github.com/repos/ski-ski/skiski-app',
        forks_url: 'https://api.github.com/repos/ski-ski/skiski-app/forks',
        keys_url: 'https://api.github.com/repos/ski-ski/skiski-app/keys{/key_id}',
        collaborators_url: 'https://api.github.com/repos/ski-ski/skiski-app/collaborators{/collaborator}',
        teams_url: 'https://api.github.com/repos/ski-ski/skiski-app/teams',
        hooks_url: 'https://api.github.com/repos/ski-ski/skiski-app/hooks',
        issue_events_url: 'https://api.github.com/repos/ski-ski/skiski-app/issues/events{/number}',
        events_url: 'https://api.github.com/repos/ski-ski/skiski-app/events',
        assignees_url: 'https://api.github.com/repos/ski-ski/skiski-app/assignees{/user}',
        branches_url: 'https://api.github.com/repos/ski-ski/skiski-app/branches{/branch}',
        tags_url: 'https://api.github.com/repos/ski-ski/skiski-app/tags',
        blobs_url: 'https://api.github.com/repos/ski-ski/skiski-app/git/blobs{/sha}',
        git_tags_url: 'https://api.github.com/repos/ski-ski/skiski-app/git/tags{/sha}',
        git_refs_url: 'https://api.github.com/repos/ski-ski/skiski-app/git/refs{/sha}',
        trees_url: 'https://api.github.com/repos/ski-ski/skiski-app/git/trees{/sha}',
        statuses_url: 'https://api.github.com/repos/ski-ski/skiski-app/statuses/{sha}',
        languages_url: 'https://api.github.com/repos/ski-ski/skiski-app/languages',
        stargazers_url: 'https://api.github.com/repos/ski-ski/skiski-app/stargazers',
        contributors_url: 'https://api.github.com/repos/ski-ski/skiski-app/contributors',
        subscribers_url: 'https://api.github.com/repos/ski-ski/skiski-app/subscribers',
        subscription_url: 'https://api.github.com/repos/ski-ski/skiski-app/subscription',
        commits_url: 'https://api.github.com/repos/ski-ski/skiski-app/commits{/sha}',
        git_commits_url: 'https://api.github.com/repos/ski-ski/skiski-app/git/commits{/sha}',
        comments_url: 'https://api.github.com/repos/ski-ski/skiski-app/comments{/number}',
        issue_comment_url: 'https://api.github.com/repos/ski-ski/skiski-app/issues/comments{/number}',
        contents_url: 'https://api.github.com/repos/ski-ski/skiski-app/contents/{+path}',
        compare_url: 'https://api.github.com/repos/ski-ski/skiski-app/compare/{base}...{head}',
        merges_url: 'https://api.github.com/repos/ski-ski/skiski-app/merges',
        archive_url: 'https://api.github.com/repos/ski-ski/skiski-app/{archive_format}{/ref}',
        downloads_url: 'https://api.github.com/repos/ski-ski/skiski-app/downloads',
        issues_url: 'https://api.github.com/repos/ski-ski/skiski-app/issues{/number}',
        pulls_url: 'https://api.github.com/repos/ski-ski/skiski-app/pulls{/number}',
        milestones_url: 'https://api.github.com/repos/ski-ski/skiski-app/milestones{/number}',
        notifications_url: 'https://api.github.com/repos/ski-ski/skiski-app/notifications{?since,all,participating}',
        labels_url: 'https://api.github.com/repos/ski-ski/skiski-app/labels{/name}',
        releases_url: 'https://api.github.com/repos/ski-ski/skiski-app/releases{/id}',
        deployments_url: 'https://api.github.com/repos/ski-ski/skiski-app/deployments',
        created_at: '2017-06-22T18:08:21Z',
        updated_at: '2017-06-23T22:48:38Z',
        pushed_at: '2017-08-03T02:23:38Z',
        git_url: 'git://github.com/ski-ski/skiski-app.git',
        ssh_url: 'git@github.com:ski-ski/skiski-app.git',
        clone_url: 'https://github.com/ski-ski/skiski-app.git',
        svn_url: 'https://github.com/ski-ski/skiski-app',
        homepage: null,
        size: 472,
        stargazers_count: 0,
        watchers_count: 0,
        language: 'JavaScript',
        has_issues: true,
        has_projects: true,
        has_downloads: true,
        has_wiki: true,
        has_pages: false,
        forks_count: 0,
        mirror_url: null,
        open_issues_count: 2,
        forks: 0,
        open_issues: 2,
        watchers: 0,
        default_branch: 'master',
      },
    },
    _links: {
      self: {
        href: 'https://api.github.com/repos/ski-ski/skiski-app/pulls/1',
      },
      html: {
        href: 'https://github.com/ski-ski/skiski-app/pull/1',
      },
      issue: {
        href: 'https://api.github.com/repos/ski-ski/skiski-app/issues/1',
      },
      comments: {
        href: 'https://api.github.com/repos/ski-ski/skiski-app/issues/1/comments',
      },
      review_comments: {
        href: 'https://api.github.com/repos/ski-ski/skiski-app/pulls/1/comments',
      },
      review_comment: {
        href: 'https://api.github.com/repos/ski-ski/skiski-app/pulls/comments{/number}',
      },
      commits: {
        href: 'https://api.github.com/repos/ski-ski/skiski-app/pulls/1/commits',
      },
      statuses: {
        href: 'https://api.github.com/repos/ski-ski/skiski-app/statuses/c10c31f9d902c9f60e6d6d964f23d66db087e8ea',
      },
    },
    merged: true,
    mergeable: null,
    rebaseable: null,
    mergeable_state: 'unknown',
    merged_by: {
      login: 'michaelmurray6298',
      id: 24865792,
      avatar_url: 'https://avatars1.githubusercontent.com/u/24865792?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/michaelmurray6298',
      html_url: 'https://github.com/michaelmurray6298',
      followers_url: 'https://api.github.com/users/michaelmurray6298/followers',
      following_url: 'https://api.github.com/users/michaelmurray6298/following{/other_user}',
      gists_url: 'https://api.github.com/users/michaelmurray6298/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/michaelmurray6298/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/michaelmurray6298/subscriptions',
      organizations_url: 'https://api.github.com/users/michaelmurray6298/orgs',
      repos_url: 'https://api.github.com/users/michaelmurray6298/repos',
      events_url: 'https://api.github.com/users/michaelmurray6298/events{/privacy}',
      received_events_url: 'https://api.github.com/users/michaelmurray6298/received_events',
      type: 'User',
      site_admin: false,
    },
    comments: 0,
    review_comments: 0,
    maintainer_can_modify: false,
    commits: 7,
    additions: 950,
    deletions: 0,
    changed_files: 17,
  });

  it('constructor accepts a passed in argument', () => {
    expect(repoPullRequest.pullRequest.id).to.equal(127281741);
  });

  it('has id property', () => {
    expect(repoPullRequest.pullRequest.id).to.equal(127281741);
  });

  it('has title property', () => {
    expect(repoPullRequest.pullRequest.title).to.equal('users migration file ');
  });

  it('has number property', () => {
    expect(repoPullRequest.pullRequest.number).to.equal(1);
  });

  it('has submittedBy property', () => {
    expect(repoPullRequest.pullRequest.user.login).to.equal('michaelmurray6298');
  });

  it('has createdAt property', () => {
    expect(repoPullRequest.pullRequest.created_at).to.equal('2017-06-23T20:21:34Z');
  });

  it('has mergeable property', () => {
    expect(repoPullRequest.pullRequest.mergeable).to.equal(null);
  });
});
