#! /usr/bin/env sh

# This script is run as the default command INSIDE the container
# and therefore does not need to issue commands via `docker-compose`

./node_modules/@databraid/env-util/index.js --bucket databraid --key gihub-api
node index.js
